let a = 10;

try 
{
    show();
} 
catch (err)
{
    console.error(err.message);
}